"""Add cascade delete to Question-Answer relationship

Revision ID: 9b0421e1a8dd
Revises: 
Create Date: 2025-05-21 00:39:48.680657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0421e1a8dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_poll_id')

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index('ix_answers_poll_id', ['poll_id'], unique=False)

    # ### end Alembic commands ###
